[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "diagrams"
version = "0.1.0"
description = "A Python project for diagrams"
readme = "README.md"
requires-python = ">=3.13"
